name: agripoa
description: "Agricultural platform for farmers and cooperatives in Tanzania."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hugeicons: ^0.0.11
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.2
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  intl: ^0.20.2
  firebase_messaging: ^15.2.6
  go_router: ^15.1.2
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  flutter_riverpod: ^2.6.1
  flex_color_scheme: ^8.2.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  fl_chart: ^0.69.0
  http: ^1.2.2
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  local_auth: ^2.3.0
  connectivity_plus: ^6.1.0
  share_plus: ^11.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
