name: agripoa
description: "Agricultural platform for farmers and cooperatives in Tanzania."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hugeicons: ^0.0.11
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.2
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  intl: ^0.20.2
  firebase_messaging: ^15.2.6
  go_router: ^15.1.2
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  flutter_riverpod: ^2.6.1
  flex_color_scheme: ^8.2.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
