List<Map<String, dynamic>> farmers = [
  {
    "id": "1",
    "name": "Andrea Lazaro Simwinga",
    "zone": "Vwawa",
    "village": "Senya",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0752741996",
    "total_number_of_trees": 25,
    "total_number_of_trees_with_fruit": 24,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "2",
    "name": "Lista Tunene Mwazembe",
    "zone": "Vwawa",
    "village": "Senya",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0756217168",
    "total_number_of_trees": 10,
    "total_number_of_trees_with_fruit": 6,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "3",
    "name": "Geofrey Kanandi Nzunda",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0747962250",
    "total_number_of_trees": 233,
    "total_number_of_trees_with_fruit": 80,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "4",
    "name": "Charles Mpanba Chenza",
    "zone": "Vwawa",
    "village": "Mbimba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0766688075",
    "total_number_of_trees": 4200,
    "total_number_of_trees_with_fruit": 2600,
    "bank_number": "01J2043435400",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "5",
    "name": "Oswald Beredon Nzelya",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0764876262",
    "total_number_of_trees": 534,
    "total_number_of_trees_with_fruit": 280,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "6",
    "name": "Rogers Isuba Mlawa",
    "zone": "Vwawa",
    "village": "Mbimba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0620242569",
    "total_number_of_trees": 54,
    "total_number_of_trees_with_fruit": 22,
    "bank_number": "01229083700",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "7",
    "name": "Boniphace Gilbert Nkoswe",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0621860541",
    "total_number_of_trees": 130,
    "total_number_of_trees_with_fruit": 10,
    "bank_number": "0152991431",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "8",
    "name": "Tenson Nkoswe",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0762811988",
    "total_number_of_trees": 200,
    "total_number_of_trees_with_fruit": 20,
    "bank_number": "0152300378300",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "9",
    "name": "Ezekia Tenson Mwampashe",
    "zone": "Vwawa",
    "village": "Mbimba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0755002517",
    "total_number_of_trees": 280,
    "total_number_of_trees_with_fruit": 140,
    "bank_number": "0150877305600",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "10",
    "name": "Raphael Haizuru Nkota",
    "zone": "Vwawa",
    "village": "Mbimba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0755670794",
    "total_number_of_trees": 250,
    "total_number_of_trees_with_fruit": 200,
    "bank_number": "0152543333800",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "11",
    "name": "Ushe Frank Mwampua",
    "zone": "Vwawa",
    "village": "Mbimba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0769859021",
    "total_number_of_trees": 500,
    "total_number_of_trees_with_fruit": 300,
    "bank_number": "0152846611600",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "12",
    "name": "Mwadas Emma",
    "zone": "Vwawa",
    "village": "Old-Vwawa",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0754404546",
    "total_number_of_trees": 280,
    "total_number_of_trees_with_fruit": 255,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "13",
    "name": "Samson Tunene Mwazembe",
    "zone": "Vwawa",
    "village": "Old-Vwawa",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0676693853",
    "total_number_of_trees": 260,
    "total_number_of_trees_with_fruit": 160,
    "bank_number": "0152567188700",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "14",
    "name": "Rosemary Sumka Mwakingili",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0717707171",
    "total_number_of_trees": 315,
    "total_number_of_trees_with_fruit": 308,
    "bank_number": "0152550869300",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "15",
    "name": "Bunka Regina Matogoro",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0787176440",
    "total_number_of_trees": 756,
    "total_number_of_trees_with_fruit": 520,
    "bank_number": "0152294864200",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "16",
    "name": "Hitson Samwel Nzunda",
    "zone": "Vwawa",
    "village": "Mbimba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0753532558",
    "total_number_of_trees": 1700,
    "total_number_of_trees_with_fruit": 600,
    "bank_number": "01J2063808900",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "17",
    "name": "Sophia Ramson Nkoswe",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0685784160",
    "total_number_of_trees": 160,
    "total_number_of_trees_with_fruit": 100,
    "bank_number": "0152625842700",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "18",
    "name": "Adam Alfred Chelelo",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 1000,
    "total_number_of_trees_with_fruit": 600,
    "bank_number": "01524767400",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "19",
    "name": "George Nzunda",
    "zone": "Vwawa",
    "village": "Kilimampimbi",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754324343",
    "total_number_of_trees": 11000,
    "total_number_of_trees_with_fruit": 6000,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "20",
    "name": "Halekwa Nyasin Mwampashe",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0712505264",
    "total_number_of_trees": 205,
    "total_number_of_trees_with_fruit": 140,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "21",
    "name": "Martha Elisha Kabuka",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0746189236",
    "total_number_of_trees": 35,
    "total_number_of_trees_with_fruit": 5,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "22",
    "name": "Alan Nyala Jengela",
    "zone": "Vwawa",
    "village": "Isangu",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0617005173",
    "total_number_of_trees": 208,
    "total_number_of_trees_with_fruit": 70,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "23",
    "name": "Godifrey Jeremia Mwakitwange",
    "zone": "Vwawa",
    "village": "Isangu",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754324343",
    "total_number_of_trees": 70,
    "total_number_of_trees_with_fruit": 12,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "24",
    "name": "Frank John Mwawalo",
    "zone": "Vwawa",
    "village": "Ichenjezya",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754613750",
    "total_number_of_trees": 20,
    "total_number_of_trees_with_fruit": 18,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "25",
    "name": "Binwelo Mdollo",
    "zone": "Vwawa",
    "village": "Senya",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 20,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "26",
    "name": "Halonga Nsansamaye",
    "zone": "Vwawa",
    "village": "Senya",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0757281367",
    "total_number_of_trees": 89,
    "total_number_of_trees_with_fruit": 50,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "27",
    "name": "Youngson Mwashiuya",
    "zone": "Vwawa",
    "village": "Senya",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0745461408",
    "total_number_of_trees": 80,
    "total_number_of_trees_with_fruit": 50,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "28",
    "name": "Silas Mshemwa Mdollo",
    "zone": "Vwawa",
    "village": "Ilembo",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754513990",
    "total_number_of_trees": 3600,
    "total_number_of_trees_with_fruit": 2600,
    "bank_number": "0152257337400",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "29",
    "name": "Gidion D. Kayange",
    "zone": "Vwawa",
    "village": "Senya",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754513990",
    "total_number_of_trees": 500,
    "total_number_of_trees_with_fruit": 450,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "30",
    "name": "Marry Zacharia Mwampamba",
    "zone": "Vwawa",
    "village": "Ilembo",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0753249653",
    "total_number_of_trees": 400,
    "total_number_of_trees_with_fruit": 400,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "31",
    "name": "Stanslaus Sojo",
    "zone": "Vwawa",
    "village": "Ilembo",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754559912",
    "total_number_of_trees": 500,
    "total_number_of_trees_with_fruit": 300,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "32",
    "name": "Willson Tusumke Mtafya",
    "zone": "Vwawa",
    "village": "Ilolo",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0755338847",
    "total_number_of_trees": 120,
    "total_number_of_trees_with_fruit": 10,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "33",
    "name": "Emmanuel Leonard Mwambe",
    "zone": "Vwawa",
    "village": "Vwawa",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0758503125",
    "total_number_of_trees": 200,
    "total_number_of_trees_with_fruit": 200,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "34",
    "name": "Anyandilwe Hans Kibona",
    "zone": "Vwawa",
    "village": "Isangu",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0763519119",
    "total_number_of_trees": 7,
    "total_number_of_trees_with_fruit": 3,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "35",
    "name": "Joachim Roman Kessy",
    "zone": "Vwawa",
    "village": "Nshanko",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754578634",
    "total_number_of_trees": 700,
    "total_number_of_trees_with_fruit": 450,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "36",
    "name": "Baton Ndekile Jengela",
    "zone": "Vwawa",
    "village": "Nshanko",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754350291",
    "total_number_of_trees": 200,
    "total_number_of_trees_with_fruit": 180,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "37",
    "name": "Gabriel usanjile Gavu",
    "zone": "Vwawa",
    "village": "Nambara",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0759907072",
    "total_number_of_trees": 500,
    "total_number_of_trees_with_fruit": 350,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "38",
    "name": "Emmanuel Elia Tweve",
    "zone": "Mlowo",
    "village": "Mlowo",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0755871003",
    "total_number_of_trees": 108,
    "total_number_of_trees_with_fruit": 65,
    "bank_number": "01520005PUV00",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "39",
    "name": "Peter Kasekwa",
    "zone": "Mlowo",
    "village": "Hatelele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0675142624",
    "total_number_of_trees": 60,
    "total_number_of_trees_with_fruit": 60,
    "bank_number": "0152298192800",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "40",
    "name": "Selestina Mwakawanga",
    "zone": "Mlowo",
    "village": "Ivwanga",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0753081390",
    "total_number_of_trees": 72,
    "total_number_of_trees_with_fruit": 13,
    "bank_number": "0152414537600",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "41",
    "name": "Patrick nzowa",
    "zone": "Mlowo",
    "village": "Igunda",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0767502277",
    "total_number_of_trees": 36,
    "total_number_of_trees_with_fruit": 8,
    "bank_number": "015229495700",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "42",
    "name": "Goodluck Mwamwezi",
    "zone": "Mlowo",
    "village": "Igunda",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0767021263",
    "total_number_of_trees": 18,
    "total_number_of_trees_with_fruit": 5,
    "bank_number": "0152396464400",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "43",
    "name": "Edward Kasiva",
    "zone": "Mlowo",
    "village": "Hatelele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0765331039",
    "total_number_of_trees": 83,
    "total_number_of_trees_with_fruit": 83,
    "bank_number": "0152688883000",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "44",
    "name": "Daud Andembwisye Bukuku",
    "zone": "Mlowo",
    "village": "Senjele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0769984399",
    "total_number_of_trees": 22,
    "total_number_of_trees_with_fruit": 22,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "45",
    "name": "Hamis Sijaona Mwaka",
    "zone": "Mlowo",
    "village": "Senjele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0756085190",
    "total_number_of_trees": 18,
    "total_number_of_trees_with_fruit": 14,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "46",
    "name": "Mikachael Issa Nsanya",
    "zone": "Mlowo",
    "village": "Senjele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 200,
    "total_number_of_trees_with_fruit": 150,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "47",
    "name": "Geofrey Miamoja Mwambwiga",
    "zone": "Mlowo",
    "village": "Senjele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0625313305",
    "total_number_of_trees": 250,
    "total_number_of_trees_with_fruit": 80,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "48",
    "name": "Asajile Satoki Kusuluka",
    "zone": "Mlowo",
    "village": "Senjele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0776170777",
    "total_number_of_trees": 92,
    "total_number_of_trees_with_fruit": 68,
    "bank_number": "0152780101600",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "49",
    "name": "Funuy Mgalla",
    "zone": "Mlowo",
    "village": "Ivwanga",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0756756215",
    "total_number_of_trees": 102,
    "total_number_of_trees_with_fruit": 13,
    "bank_number": "22908600899",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "50",
    "name": "Hebron Mwasimba Mwamlima",
    "zone": "Mlowo",
    "village": "Hatelele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0757195532",
    "total_number_of_trees": 78,
    "total_number_of_trees_with_fruit": 40,
    "bank_number": "0152845580700",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "51",
    "name": "Erick Shitindi",
    "zone": "Mlowo",
    "village": "Hatelele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0722244051",
    "total_number_of_trees": 386,
    "total_number_of_trees_with_fruit": 342,
    "bank_number": "01J2019361600",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "52",
    "name": "Asajile Ndile",
    "zone": "Mlowo",
    "village": "Mahenje",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0758136332",
    "total_number_of_trees": 100,
    "total_number_of_trees_with_fruit": 60,
    "bank_number": "0152336943000",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "53",
    "name": "Getrude Kalinga",
    "zone": "Mlowo",
    "village": "Mlowo",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0762818173",
    "total_number_of_trees": 20,
    "total_number_of_trees_with_fruit": 20,
    "bank_number": "0150890710500",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "54",
    "name": "Amnoni Mwachipo Mwasile",
    "zone": "Mlowo",
    "village": "Mlowo",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0752334266",
    "total_number_of_trees": 100,
    "total_number_of_trees_with_fruit": 70,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "55",
    "name": "Asafu Amulike Sanga",
    "zone": "Mlowo",
    "village": "Mlowo",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0733720292",
    "total_number_of_trees": 130,
    "total_number_of_trees_with_fruit": 130,
    "bank_number": "7152844912000",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "56",
    "name": "Nicko Mathias Nkwabi",
    "zone": "Mlowo",
    "village": "Mahenje",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0655648062",
    "total_number_of_trees": 250,
    "total_number_of_trees_with_fruit": 60,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "57",
    "name": "Abraham Amos Shitibdi",
    "zone": "Mlowo",
    "village": "Hatelele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0749971294",
    "total_number_of_trees": 35,
    "total_number_of_trees_with_fruit": 5,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "58",
    "name": "Mawazo Edson Mwasenga",
    "zone": "Mlowo",
    "village": "Zelezeta",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0762424669",
    "total_number_of_trees": 185,
    "total_number_of_trees_with_fruit": 73,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "59",
    "name": "Musabera Stella Kamatura",
    "zone": "Mlowo",
    "village": "Makuva",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0759849827",
    "total_number_of_trees": 114,
    "total_number_of_trees_with_fruit": 35,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "60",
    "name": "Leonard Joseph Mbilinyi",
    "zone": "Mlowo",
    "village": "Mahenje",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754925842",
    "total_number_of_trees": 142,
    "total_number_of_trees_with_fruit": 109,
    "bank_number": "0112068007700",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "61",
    "name": "Lukumbuka Anyelukisye Kyomo",
    "zone": "Mlowo",
    "village": "Mlowo",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0755915825",
    "total_number_of_trees": 60,
    "total_number_of_trees_with_fruit": 50,
    "bank_number": "0152664022500",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "62",
    "name": "Jonas Ambonisye Mwailafu",
    "zone": "Mlowo",
    "village": "Mlowo",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0757339859",
    "total_number_of_trees": 60,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "63",
    "name": "Auton Samson Simbeye",
    "zone": "Mlowo",
    "village": "Kakozi",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0622382405",
    "total_number_of_trees": 219,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "64",
    "name": "Adam Kalenga Kisimani",
    "zone": "Mlowo",
    "village": "Hatelele",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754623894",
    "total_number_of_trees": 3700,
    "total_number_of_trees_with_fruit": 2100,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "65",
    "name": "Yohana Mwamlima Mwalimu",
    "zone": "Mlowo",
    "village": "Mlowo",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0622068507",
    "total_number_of_trees": 35,
    "total_number_of_trees_with_fruit": 12,
    "bank_number": "0152978651800",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "66",
    "name": "God Brackson Tandala",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0758397637",
    "total_number_of_trees": 100,
    "total_number_of_trees_with_fruit": 100,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "67",
    "name": "Elia Satieli Ntandala",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0629266556",
    "total_number_of_trees": 500,
    "total_number_of_trees_with_fruit": 300,
    "bank_number": "0152687198200",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "68",
    "name": "Justine Baton Mwambwalo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0629266761",
    "total_number_of_trees": 100,
    "total_number_of_trees_with_fruit": 50,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "69",
    "name": "Kanisa la Jeshi la Wokovu",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0622648081",
    "total_number_of_trees": 5,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "70",
    "name": "Simon Kingson Mwalyala",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0628323789",
    "total_number_of_trees": 145,
    "total_number_of_trees_with_fruit": 32,
    "bank_number": "0152687198200",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "71",
    "name": "Watson Adson Hansunga",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0767022420",
    "total_number_of_trees": 100,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "72",
    "name": "Zacharia Ningson Mwalyala",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0623999055",
    "total_number_of_trees": 17,
    "total_number_of_trees_with_fruit": 1,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "73",
    "name": "Jagro Shikombora Msyaliha",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0627653790",
    "total_number_of_trees": 200,
    "total_number_of_trees_with_fruit": 15,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "74",
    "name": "Razaro Satiel Ntandala",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "062626080",
    "total_number_of_trees": 55,
    "total_number_of_trees_with_fruit": 3,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "75",
    "name": "Daudi Adson Hansunga",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0623998771",
    "total_number_of_trees": 60,
    "total_number_of_trees_with_fruit": 3,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "76",
    "name": "Yusti Watson Mwaweza",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0615004631",
    "total_number_of_trees": 5,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "77",
    "name": "Landan Satiel Ntantala",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0612483182",
    "total_number_of_trees": 71,
    "total_number_of_trees_with_fruit": 71,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "78",
    "name": "Paul Gopegala Mwalyema",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 50,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "79",
    "name": "Julius Mwasenga Mwambwalo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "062100192",
    "total_number_of_trees": 30,
    "total_number_of_trees_with_fruit": 30,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "80",
    "name": "Roma Mwajenda Mwambwalo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0629266653",
    "total_number_of_trees": 30,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "81",
    "name": "Joel Julius Mwambwalo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 20,
    "total_number_of_trees_with_fruit": 1,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avodo"],
  },
  {
    "id": "82",
    "name": "Watson Youngson Ntengwi",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0629269103",
    "total_number_of_trees": 300,
    "total_number_of_trees_with_fruit": 150,
    "bank_number": "0152689800100",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "83",
    "name": "Huruma Edson Mwambwalo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0623188075",
    "total_number_of_trees": 24,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "84",
    "name": "Ibrahim Watson Ntengwi",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0621056858",
    "total_number_of_trees": 10,
    "total_number_of_trees_with_fruit": 1,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "85",
    "name": "Ayub Julius Mwalyema",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 4,
    "total_number_of_trees_with_fruit": 4,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "86",
    "name": "Juma Willson Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0621470041",
    "total_number_of_trees": 4,
    "total_number_of_trees_with_fruit": 4,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "87",
    "name": "Juma Willson Mwaweza",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 3,
    "total_number_of_trees_with_fruit": 3,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "88",
    "name": "Nelson Mkinga Mwambwalo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0629269053",
    "total_number_of_trees": 60,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "62610004952",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "89",
    "name": "Kambombo Mkinga Mwambwalo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 10,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "90",
    "name": "Jumapili Andrew Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 14,
    "total_number_of_trees_with_fruit": 1,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "91",
    "name": "Safari Younson Ntengwi",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0623190096",
    "total_number_of_trees": 70,
    "total_number_of_trees_with_fruit": 1,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "92",
    "name": "Gabriel Watson Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 1,
    "total_number_of_trees_with_fruit": 1,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "93",
    "name": "Razaro Andrew Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 14,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "94",
    "name": "Jordan Padili Ntandala",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0627467741",
    "total_number_of_trees": 5,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "95",
    "name": "Geofrey Edward Mwahalende",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0744277944",
    "total_number_of_trees": 5,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "96",
    "name": "Ribson Hasajira Mwashoga",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 10,
    "total_number_of_trees_with_fruit": 10,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "97",
    "name": "Mzunda London George",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0625707046",
    "total_number_of_trees": 100,
    "total_number_of_trees_with_fruit": 60,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "98",
    "name": "Joshua Yohana Mwambogola",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 47,
    "total_number_of_trees_with_fruit": 47,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "99",
    "name": "kalani Yisambi hansuli",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0617280917",
    "total_number_of_trees": 50,
    "total_number_of_trees_with_fruit": 18,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "100",
    "name": "Alipo Eliakimu Mwasenga",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0623998717",
    "total_number_of_trees": 750,
    "total_number_of_trees_with_fruit": 700,
    "bank_number": "0152503391100",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "101",
    "name": "Bahari Mwachusa Mwambwiga",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 1,
    "total_number_of_trees_with_fruit": 1,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "102",
    "name": "Jumamosi Shikombola Msyaliha",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0626255718",
    "total_number_of_trees": 1000,
    "total_number_of_trees_with_fruit": 250,
    "bank_number": "62210017090",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "103",
    "name": "Baraka Eliakimu Mwasenga",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0757111631",
    "total_number_of_trees": 110,
    "total_number_of_trees_with_fruit": 70,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "104",
    "name": "Saulon Yohana Mwambogolo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0624722539",
    "total_number_of_trees": 20,
    "total_number_of_trees_with_fruit": 14,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "105",
    "name": "Hamisi Hainanje Ntandala",
    "zone": "Idiwili",
    "village": "Ululu",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0757841313",
    "total_number_of_trees": 120,
    "total_number_of_trees_with_fruit": 150,
    "bank_number": "0152691130700",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "106",
    "name": "Alexander Aron Mwampashe",
    "zone": "Idiwili",
    "village": "Ululu",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0785018390",
    "total_number_of_trees": 150,
    "total_number_of_trees_with_fruit": 150,
    "bank_number": "0152299035800",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "107",
    "name": "Yona Samzuma Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0626282553",
    "total_number_of_trees": 900,
    "total_number_of_trees_with_fruit": 40,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "108",
    "name": "Christopher Elias Mwambogolo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0747994736",
    "total_number_of_trees": 1020,
    "total_number_of_trees_with_fruit": 934,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "109",
    "name": "Widson Mpewa Ntandala",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0629455193",
    "total_number_of_trees": 105,
    "total_number_of_trees_with_fruit": 105,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "110",
    "name": "Jeki Posta Mwambogolo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0683581557",
    "total_number_of_trees": 100,
    "total_number_of_trees_with_fruit": 60,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "111",
    "name": "Thomas Simeon Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0623999053",
    "total_number_of_trees": 90,
    "total_number_of_trees_with_fruit": 10,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "112",
    "name": "Amos Gimson Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0625949220",
    "total_number_of_trees": 76,
    "total_number_of_trees_with_fruit": 6,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "113",
    "name": "Watson Katusanje Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0784582868",
    "total_number_of_trees": 50,
    "total_number_of_trees_with_fruit": 15,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "114",
    "name": "Joshua Dickson Mwakamanyale",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0626613768",
    "total_number_of_trees": 600,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "115",
    "name": "Cleopa Adson Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0615111409",
    "total_number_of_trees": 179,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "116",
    "name": "Gabriel Adson Mboma",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0784692856",
    "total_number_of_trees": 118,
    "total_number_of_trees_with_fruit": 97,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "117",
    "name": "Shukuru Mangen Mwameza",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0622178550",
    "total_number_of_trees": 12,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "118",
    "name": "Shanel Emmanuel Mwasenga",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Female",
    "date_of_birth": "1970-01-01",
    "phone": "0625711262",
    "total_number_of_trees": 80,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "119",
    "name": "Thobias Ernest mwameza",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": null,
    "total_number_of_trees": 40,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "120",
    "name": "Samson Nyembe Mwaharende",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0756994910",
    "total_number_of_trees": 70,
    "total_number_of_trees_with_fruit": 10,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "121",
    "name": "Cornest Samson Mwahalende",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0624285174",
    "total_number_of_trees": 6,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": null,
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "122",
    "name": "Festo Jamson Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0623998718",
    "total_number_of_trees": 610,
    "total_number_of_trees_with_fruit": 180,
    "bank_number": "0152688286900",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "123",
    "name": "Sadoki Wile Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0625285319",
    "total_number_of_trees": 50,
    "total_number_of_trees_with_fruit": 25,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "124",
    "name": "Festo Mashaka Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0612516276",
    "total_number_of_trees": 30,
    "total_number_of_trees_with_fruit": 20,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "125",
    "name": "Yohana Wenela Shitindi",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0746894879",
    "total_number_of_trees": 50,
    "total_number_of_trees_with_fruit": 50,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "126",
    "name": "Edwin Obed Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0623159530",
    "total_number_of_trees": 40,
    "total_number_of_trees_with_fruit": 5,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "127",
    "name": "Joel Moris Mwambogolo",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0621135074",
    "total_number_of_trees": 80,
    "total_number_of_trees_with_fruit": 55,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "128",
    "name": "Dameki Babuya Ntandala",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0629266590",
    "total_number_of_trees": 50,
    "total_number_of_trees_with_fruit": 50,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "129",
    "name": "Bunge Sauni Mzumbwe",
    "zone": "Idiwili",
    "village": "Ilomba",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0627130773",
    "total_number_of_trees": 53,
    "total_number_of_trees_with_fruit": 20,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "130",
    "name": "Saston Nyerere Nzowa",
    "zone": "Shiwinga",
    "village": "Iwezi",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0745538451",
    "total_number_of_trees": 420,
    "total_number_of_trees_with_fruit": 300,
    "bank_number": "0152504262100",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "131",
    "name": "Asungwile Tweve",
    "zone": "Shiwinga",
    "village": "Shiwinga",
    "gender": "Unknown",
    "date_of_birth": "1970-01-01",
    "phone": "0764882063",
    "total_number_of_trees": 300,
    "total_number_of_trees_with_fruit": 100,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "132",
    "name": "Philemon Msongole",
    "zone": "Shiwinga",
    "village": "Iwezi",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0754072612",
    "total_number_of_trees": 240,
    "total_number_of_trees_with_fruit": 0,
    "bank_number": "0112598249900",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
  {
    "id": "133",
    "name": "Edwin Mela",
    "zone": "Shiwinga",
    "village": "Iwezi",
    "gender": "Male",
    "date_of_birth": "1970-01-01",
    "phone": "0766270404",
    "total_number_of_trees": 116,
    "total_number_of_trees_with_fruit": 88,
    "bank_number": "0",
    "bank_name": "Unknown",
    "crops": ["avocado"],
  },
];
